
project_id = "zbhonwmadpxokkcbfpgp"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions]
[functions.delete-cloudinary-asset]
verify_jwt = true
[functions.cloudinary-upload]
verify_jwt = true
