
project_id = "zbhonwmadpxokkcbfpgp"

# Storage configuration
[storage]
file_size_limit = 50000000  # 50MB file size limit

# Cache Control Headers
[storage.cache_control]
# Cache images for 30 days
"*.jpg" = "max-age=2592000, public"
"*.jpeg" = "max-age=2592000, public"
"*.png" = "max-age=2592000, public"
"*.gif" = "max-age=2592000, public"
"*.webp" = "max-age=2592000, public"
"*.avif" = "max-age=2592000, public"
# Cache CSS and JavaScript files for 1 week
"*.css" = "max-age=604800, public"
"*.js" = "max-age=604800, public"
# Cache fonts for 30 days
"*.woff" = "max-age=2592000, public"
"*.woff2" = "max-age=2592000, public"
"*.ttf" = "max-age=2592000, public"
# Cache manifest files for 1 hour
"*.json" = "max-age=3600, public"

[api]
port = 8000
schemas = []
extra_search_path = ["extensions"]
max_rows = 1000
request_timeout_seconds = 10

