
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbhonwmadpxokkcbfpgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiaG9ud21hZHB4b2trY2JmcGdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Nzg3MzMsImV4cCI6MjA2MjU1NDczM30.6q6a59ijQ1f7xwWH5DhP82svjU7PluXPIOQC9D9zwrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  },
  global: {
    headers: {
      'Content-Type': 'application/json'
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Debug log to check auth status when client is initialized
supabase.auth.getSession().then(({ data }) => {
  if (data.session) {
    console.log('User is authenticated with ID:', data.session.user.id);
  } else {
    console.log('No active session found');
  }
}).catch(error => {
  console.error('Error checking auth session:', error);
});
